config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search', to: 'searches#search'

  resources :books do
    resource :favorites,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  
  has_many :room_users
  # UsersテーブルとRoomsテーブルは多対多の関係
  # そのため、中間テーブルとしてroom_usersテーブルをおき、その情報を管理します。
  has_many :messages
  # またRoomsでは、複数（2人）のユーザーが複数のメッセージを送る多対多の関係なので、
  # これも中間テーブルとしてMessagesテーブルをおき、その情報を管理します。
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  # following_user:中間テーブルを通してfollowedモデルのフォローされる側を取得すること
  has_many :follower_user, through: :followed, source: :follower
  # follower_user:中間テーブルを通してfollowerモデルのフォローする側を取得すること

# ユーザーをフォローするメソッド
  def follow(user_id)
    follower.create(followed_id: user_id)
  end
  # ユーザーのフォローを外すメソッド
  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  #フォローの確認を行うメソッド　していればtrueを返す
  def following?(user)
    following_user.include?(user)
  end

  attachment :profile_image, destroy: false

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @currentRoomUser = RoomUser.where(user_id: current_user.id)
    #current_userが既にルームに参加しているか判断
    @receiveUser = RoomUser.where(user_id: @user.id)
    #他の@userがルームに参加しているか判断
    @books = @user.books
    @book = Book.new
    @following_users = @user.following_user
    @follower_users = @user.follower_user

    unless @user.id == current_user.id  #current_userと@userが一致していなければ
      @currentRoomUser.each do |cu|  #current_userが参加しているルームを取り出す
        @receiveUser.each do |u|  #@userが参加しているルームを取り出す
          if cu.room_id == u.room_id  #current_userと@userのルームが同じか判断(既にルームが作られているか)
            @haveRoom = true  #falseの時(同じじゃない時)の条件を記述するために変数に代入
            @roomId = cu.room_id  #ルームが共通しているcurrent_userと@userに対して変数を指定
          end
        end
      end
      unless @haveroom  #ルームが同じじゃなければ
        @room = Room.new  #新しいインスタンスを生成
        @roomuser = RoomUser.new  #新しいインスタンスを生成
      end
    end

  end


  def index
    @users = User.all
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user==current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def follows
    @user = User.find(params[:id])
    @follows = @user.following_user
  end

  def followers
    @user = User.find(params[:id])
    @followed = @user.follower_user
  end


  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th>
      <%= link_to follows_user_path(user) do %>
      <%= user.following_user.count %>
      <%end%>
    </th>
  </tr>
  <tr>
    <th>followers</th>
    <th>
      <%= link_to followers_user_path(user) do %>
      <%=user.follower_user.count %>
      <%end%>
    </th>
  </tr>
</table>

<div class='row'>
  <% if current_user != user %>
    <% if current_user.following?(user) %>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn-sm btn-danger" %>
    <%else%>
      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn-sm btn-success" %>
    <%end%>
  <%end%>

  <% unless user.id == current_user.id %>
  <!--現在ログインしているユーザーではない場合-->
    <% if (current_user.followed_by? user) && (user.followed_by? current_user) %>
    <!--相互フォロー状態の時という条件-->
      <% if haveRoom == true %> <!--すでにチャットルームが作成されている場合は-->
        <%= link_to "ダイレクトメッセージ", room_path %>  <!--そのチャットルームに遷移するボタンを表示-->
      <%else%>
        <%= form_with model: room, local: true do |f| %>  <!--roomsテーブルに情報を送信-->
          <%= fields_for roomuser do |r| %>               <!--room_usersテーブルに情報を送信-->

          <!--fields_forを使うことによって異なるモデル(子モデル)を編集できるようになる。-->
          <!--例：Roomモデルに紐付くRoomUserモデル-->

            <%= r.hidden_field :user_id, value: user.id %>  <!--room_usersテーブルにuser_idを含める-->
          <%end%>
          <%= f.submit "chatを始める" %>
        <%end%>
      <%end%>
    <%end%>
  <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <%end%>

</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h2>Follower Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @followed.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.following_user.count %></td>
        <td>フォロワー数:<%= user.follower_user.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/follows.html.erb
<h2>Follow Users</h2>
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @follows.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数:<%= user.following_user.count %></td>
        <td>フォロワー数:<%= user.follower_user.count %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user, following_users: @following_users, follower_users: @follower_users %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user, following_users: @following_users, follower_users: @follower_users, haveRoom: @haveRoom, room: @room, roomuser: @RoomUser %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>