config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search', to: 'searches#search'

  resources :books do
    resource :favorites,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end

  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :follows, :followers
    end
    resource :relationships, only: [:create, :destroy]
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    @model = params["model"]
    @method = params["method"]
    @content = params["content"]
    @records = search_for(@model, @method, @content)
  end

  private

  def search_for(model, method, content)

    if model == 'user'

      if method == 'perfect_match'
        User.where(name: content)
        # 完全一致
      elsif method == 'forward_match'
        User.where('name LIKE ?', +content+'%')
        # 前方一致
      elsif method == 'backward_match'
        User.where('name LIKE ?', '%'+content)
        # 後方一致
      elsif method == 'partial_match'
        User.where('name LIKE ?', '%'+content+'%' )
        # 部分一致
      end

    elsif model =='book'

      if method == 'perfect_match'
        Book.where(title: content)

      elsif method == 'forward_match'
        Book.where('title LIKE ?', +content+'%')

      elsif method == 'backward_match'
        Book.where('title LIKE ?', '%'+content)

      elsif method == 'partial_match'
        Book.where('title LIKE ?', '%'+content+'%')
      end

    end

  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag 'content' %>
    <%= select_tag 'model', options_for_select({"User" => "user", "Book" => "book"}) %>
    <%= select_tag 'method', options_for_select({"完全一致" => "perfect_match", "前方一致" => "forward_match", "後方一致" => "backward_match", "部分一致" => "partial_match"}) %>
    <%= submit_tag '検索' %>
  <%end%>
<%end%>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h2>Users search for"<%= @content %>"</h2>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
          <%= link_to user_path(user) do %>
            <td><%= user.name %></td>
          <%end%>
        </tr>
      <%end%>
    </tbody>
  </table>

<%else @model == 'book' %>

  <h2>Books search for"<%= @content %>"</h2>
  <table class='table'>
    <thead>
      <tr>
        <th colspan="3"></th>
        <th>title</th>
        <th>opinion</th>
      </tr>
    </thead>
    <tbody>
      <% @records.each do |book| %>
        <tr>
          <td><%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
          <%= link_to book_path(book) do %>
            <td><%= book.title %></td>
          <%end%>
          <td><%= book.body %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
<%end%>